name: Format

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Install npm v8 (workaround for https://github.com/creyD/prettier_action/issues/113)
        run: npm i -g npm@8

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write .
          only_changed: True
          commit_message: 'chore: format'
